import os
if os.name == "nt":
	t = ["mingw"]
else:
	t = ["default"]
env = Environment(tools = t)
env.Program("bin/proto", Glob("src/*/*.cpp"), CPPPATH = ["include"], LIBS = ["sfml-system", "sfml-window", "sfml-graphics", "lua5.1"])
